[package]
name = "rust_cuda_demo"
version = "0.0.0"
edition = "2021"

[[bench]]
name = "sgemm"
harness = false

[dependencies]
thiserror = "2.0.4"

[build-dependencies]
cc = "1.2.2"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
