[package]
name = "rust_cuda_demo"
version = "0.0.0"
edition = "2021"

[[bench]]
name = "sgemm"
harness = false

[build-dependencies]
cc = "1.2.3"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
